# Generated by Django 3.1.7 on 2021-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='key',
            field=models.CharField(default='foobar', max_length=20),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='key_description',
            field=models.CharField(default='foobar', max_length=50),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='profile_bio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='profile_nickname',
            field=models.CharField(max_length=20),
        ),
    ]
