# Generated by Django 3.1.7 on 2021-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0003_auto_20210408_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThisWeekModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Task'), (2, 'Event'), (3, 'Note')], null=True)),
                ('item_details', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='keymodel',
            name='key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='keymodel',
            name='key_description',
            field=models.CharField(max_length=50),
        ),
    ]
