# Generated by Django 3.1.7 on 2021-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0004_auto_20210408_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thisweekmodel',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Task', 'Task'), ('Event', 'Event'), ('Note', 'Note')], max_length=20, null=True),
        ),
    ]
