# Generated by Django 3.1.7 on 2021-04-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0005_auto_20210408_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, choices=[('Task', 'Task'), ('Event', 'Event'), ('Note', 'Note')], max_length=20, null=True)),
                ('item_details', models.CharField(max_length=50)),
            ],
        ),
    ]
