# Generated by Django 3.1.7 on 2021-04-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0006_todaymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/default.jpg', upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='image',
        ),
    ]
