# Generated by Django 3.1.7 on 2021-04-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0007_auto_20210409_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_nickname', models.CharField(max_length=20)),
                ('profile_bio', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='profile_bio',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='profile_nickname',
        ),
        migrations.AlterField(
            model_name='profileimagemodel',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
